---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: gnis-pv
  labels:
    type: local
spec:
  storageClassName: "manual"
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 75Gi
  hostPath:
    path: "/data"
