---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: gnis
  name: gnis-pvc
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 75Gi
