apiVersion: v1
kind: Service
metadata:
  name: graphdb
spec:
  ports:
  - name: graphdb
    port: 7200
    targetPort: 7200
  selector:
    app: graphdb
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  type: ClusterIP
