---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: gnis
  name: test-pvc
spec:
  storageClassName: "manual"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
